services:
  - type: web
    name: backend-cade-meu-pacote
    env: node
    branch: main
    rootDir: backend
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run start:prod
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
